### ISSUE TITLE
compile error with qt4

### ISSUE THREAD

**Issue by netpipe** [socec/HorseRacing#1]
network/raceclient.cpp:35:40: error: ‘AnyIPv4’ is not a member of ‘QHostAddress’
     multicastSocket.bind(QHostAddress::AnyIPv4, multicastPort, QUdpSocket::ShareAddress);

**Comment by socec** [comment]
I've actually never used Qt 4 to compile this project. Sadly, there is no information about supported Qt versions here, so shame on me.

Please run Qt 5. To be specific, I use Qt 5.7.

**Comment by netpipe** [comment]
tried to compile with qt 5.7 on linux and got same error

**Comment by socec** [comment]
I'm using:
Qt Creator 4.0.2 for Linux
Based on Qt 5.7.0 (GCC 4.9.1 20140922 (Red Hat 4.9.1-10), 64 bit)

I've cloned a fresh version of the repo, opened the .pro file in Qt Creator and it compiled successfully.

I'm not sure I can reproduce your problem :(
